name: Python

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: set
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: print
        run: python -c "import sys; print(sys.version)" > python-version-${{ matrix.python-version }}.txt

      - name: up
        uses: actions/upload-artifact@v3
        with:
          name: python-version-${{ matrix.python-version }}
          path: python-version-${{ matrix.python-version }}.txt
